import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  FiArrowLeft, FiChevronDown, FiShield, FiSearch, FiFileText, FiX, FiAlertTriangle, FiActivity, FiUser, FiZap 
} from 'react-icons/fi';
import { apiService } from '../services/api';

const Analytics = ({ drugName, file, onBack }) => {
  const [expandedSection, setExpandedSection] = useState(null);
  const [showSummary, setShowSummary] = useState(false);
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        const result = await apiService.analyzeDrug(file, drugName);
        setData(result);
      } catch (err) {
        setError(err.message);
        console.error('Failed to fetch analysis data:', err);
      } finally {
        setLoading(false);
      }
    };
    
    if (file && drugName) {
      fetchData();
    }
  }, [file, drugName]);

  if (loading) {
    return (
      <div className="min-h-screen w-full bg-[#050505] text-white font-sans flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-white mx-auto mb-4"></div>
          <p>Analyzing genetic data...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen w-full bg-[#050505] text-white font-sans flex items-center justify-center">
        <div className="text-center">
          <p className="text-red-500 mb-4">Error: {error}</p>
          <button onClick={onBack} className="px-4 py-2 bg-white text-black rounded-lg">Go Back</button>
        </div>
      </div>
    );
  }

  if (!data) {
    return (
      <div className="min-h-screen w-full bg-[#050505] text-white font-sans flex items-center justify-center">
        <div className="text-center">
          <p>No data available</p>
          <button onClick={onBack} className="px-4 py-2 bg-white text-black rounded-lg mt-4">Go Back</button>
        </div>
      </div>
    );
  }

  const isCritical = data.risk_assessment.risk_label === "Ineffective" || data.risk_assessment.severity === "high";
  const primaryVariant = data.pharmacogenomic_profile.detected_variants[0];

  // KPI Configuration
  const kpis = [
    { label: 'Parsing', val: 'SUCCESS', icon: <FiActivity className="text-emerald-500" />, sub: 'VCF Verified' },
    { label: 'Confidence', val: `${data.risk_assessment.confidence_score * 100}%`, icon: <FiZap className="text-blue-400" />, sub: 'Model Precision' },
    { label: 'Patient ID', val: data.patient_id, icon: <FiUser />, sub: 'Subject Identity' },
    { label: 'Diplotype', val: data.pharmacogenomic_profile.diplotype, icon: <FiShield />, sub: 'Genetic Result', highlight: isCritical },
    { label: 'Variant RSID', val: primaryVariant.rsid, icon: <FiSearch />, sub: 'Reference SNP' },
    { label: 'Impact', val: primaryVariant.impact, icon: <FiAlertTriangle />, sub: 'Clinical Risk', alert: primaryVariant.impact === 'Critical' },
  ];

  const downloadPDF = () => {
    // Create PDF content with summary
    const pdfContent = `
PHARMGUARD CLINICAL REPORT
============================

PATIENT INFORMATION
-----------------
Patient ID: ${data.patient_id}
Drug: ${data.drug}
Analysis Date: ${data.timestamp}

GENETIC ANALYSIS
-----------------
Primary Gene: ${data.pharmacogenomic_profile.primary_gene}
Diplotype: ${data.pharmacogenomic_profile.diplotype}
Phenotype: ${data.pharmacogenomic_profile.phenotype}

RISK ASSESSMENT
-----------------
Risk Level: ${data.risk_assessment.risk_label}
Confidence: ${(data.risk_assessment.confidence_score * 100)}%
Severity: ${data.risk_assessment.severity}

CLINICAL RECOMMENDATION
------------------------
${data.clinical_recommendation.recommendation}
Evidence: ${data.clinical_recommendation.evidence}

GENETIC SUMMARY
----------------
${data.llm_generated_explanation.summary}

VARIANT DETAILS
---------------
${data.pharmacogenomic_profile.detected_variants.map(v => 
  `RSID: ${v.rsid}\nImpact: ${v.impact}\nDetail: ${v.detail}`
).join('\n\n')}

Report generated by PharmGuard v2.0
© 2026 PharmGuard Systems
    `;

    // Create blob and download
    const blob = new Blob([pdfContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `PharmGuard_Report_${data.patient_id}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen w-full bg-[#050505] text-white font-sans p-4 md:p-8 relative selection:bg-red-500 selection:text-white">
      <div className="fixed inset-0 bg-[radial-gradient(circle_at_50%_0%,#111_0%,transparent_70%)] pointer-events-none" />
      
      <main className="max-w-7xl mx-auto relative z-10">
        
        {/* --- Header & Navigation --- */}
        <nav className="flex items-center justify-between mb-8">
          <button onClick={onBack} className="group flex items-center gap-4 text-white/40 hover:text-white transition-all">
            <div className="w-10 h-10 bg-white border border-white/10 rounded-full flex items-center justify-center group-hover:scale-110 transition-all"><FiArrowLeft className="text-black" /></div>
            <span className="text-[10px] tracking-[0.3em] uppercase font-bold">PharmGuard</span>
          </button>
          <div className="flex gap-3">
            <button onClick={() => setShowSummary(true)} className="px-5 py-2.5 rounded-xl bg-white/5 border border-white/10 text-[10px] font-bold uppercase tracking-widest hover:bg-white/10 transition-all">Report</button>
            <button onClick={downloadPDF} className="px-5 py-2.5 rounded-xl bg-white text-black text-[10px] font-bold uppercase tracking-widest hover:scale-105 transition-all">Export PDF</button>
          </div>
        </nav>

        {/* --- KPI Grid Section --- */}
        <div className="grid grid-cols-2 lg:grid-cols-6 gap-4 mb-8">
          {kpis.map((kpi, idx) => (
            <motion.div 
              key={idx}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.1 }}
              className={`p-6 rounded-3xl border ${kpi.alert ? 'bg-red-500/10 border-red-500/40 shadow-[0_0_20px_rgba(239,68,68,0.1)]' : 'bg-white/[0.03] border-white/10'}`}
            >
              <div className="flex items-center gap-2 mb-3 text-white/30">
                <span className="text-sm">{kpi.icon}</span>
                <span className="text-[9px] font-black uppercase tracking-widest">{kpi.label}</span>
              </div>
              <p className={`text-lg font-mono font-bold leading-none mb-1 ${kpi.alert ? 'text-red-500' : 'text-white'}`}>
                {kpi.val}
              </p>
              <p className="text-[8px] opacity-30 font-bold uppercase tracking-tighter">{kpi.sub}</p>
            </motion.div>
          ))}
        </div>

        {/* --- Hero Analysis Card --- */}
        <div className="grid grid-cols-1 gap-6 mb-12">
          <motion.div 
            initial={{ opacity: 0, scale: 0.98 }} animate={{ opacity: 1, scale: 1 }}
            className={`p-10 md:p-14 rounded-[3rem] border ${isCritical ? 'border-red-600/50 bg-red-600/5 shadow-[0_0_60px_rgba(220,38,38,0.1)]' : 'border-white/10 bg-white/[0.02]'} transition-all`}
          >
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-8">
              <div>
                <div className="flex items-center gap-3 mb-6">
                  {isCritical && (
                    <span className="flex items-center gap-2 px-3 py-1 bg-red-600 text-[10px] font-black uppercase tracking-tighter rounded-lg text-white animate-pulse">
                      <FiAlertTriangle /> Critical Interference Detected
                    </span>
                  )}
                  <span className="text-[10px] tracking-[0.4em] text-white/40 uppercase font-black">Pharmacology Report</span>
                </div>
                <h1 className="text-4xl md:text-6xl font-black tracking-tighter uppercase leading-none mb-2">{data.drug}</h1>
                <p className="text-white/40 font-medium tracking-[0.2em] uppercase text-xs">Primary Gene: {data.pharmacogenomic_profile.primary_gene} // {data.pharmacogenomic_profile.phenotype}</p>
              </div>
            </div>
          </motion.div>
        </div>

        {/* --- Variant Details Explorer --- */}
        <div className="bg-white/[0.02] border border-white/10 rounded-[2.5rem] overflow-hidden">
          <div className="px-10 py-6 border-b border-white/10 flex justify-between items-center bg-white/[0.01]">
            <div className="flex items-center gap-3">
              <FiSearch className="text-white/30" />
              <h4 className="text-[10px] font-black text-white/30 uppercase tracking-[0.4em]">Extended Genetic Sequence Detail</h4>
            </div>
          </div>
          
          {data.pharmacogenomic_profile.detected_variants.map((v, i) => (
            <div key={v.rsid}>
              <button 
                onClick={() => setExpandedSection(expandedSection === i ? null : i)}
                className="w-full flex justify-between p-10 items-center text-left hover:bg-white/[0.04] transition-all"
              >
                <div className="flex gap-16 items-center">
                   <div>
                    <p className="text-[9px] opacity-40 font-black uppercase tracking-tighter mb-1">Variant Identity</p>
                    <p className="text-lg font-mono font-bold">{v.rsid}</p>
                  </div>
                  <div>
                    <p className="text-[9px] opacity-40 font-black uppercase tracking-tighter mb-1">Functional Impact</p>
                    <p className={`text-lg font-bold uppercase tracking-widest ${v.impact === 'Critical' ? 'text-red-600' : 'text-white'}`}>
                      {v.impact}
                    </p>
                  </div>
                </div>
                <FiChevronDown className={`text-2xl transition-transform duration-500 ${expandedSection === i ? 'rotate-180' : 'opacity-20'}`} />
              </button>
              <AnimatePresence>
                {expandedSection === i && (
                  <motion.div initial={{ height: 0 }} animate={{ height: 'auto' }} exit={{ height: 0 }} className="overflow-hidden bg-white/[0.01]">
                    <div className="p-10 text-lg text-white/50 border-t border-white/5 leading-relaxed italic max-w-4xl">
                      {v.detail}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          ))}
        </div>

        {/* --- Summary Modal --- */}
        <AnimatePresence>
          {showSummary && (
            <div className="fixed inset-0 z-[100] flex items-center justify-center p-6 bg-black/95 backdrop-blur-2xl">
              <motion.div 
                initial={{ y: 50, opacity: 0 }} animate={{ y: 0, opacity: 1 }} exit={{ y: 50, opacity: 0 }} 
                className="relative w-full max-w-2xl bg-white text-black p-12 md:p-16 rounded-[4rem] shadow-2xl"
              >
                <button onClick={() => setShowSummary(false)} className="absolute top-10 right-10 text-black/20 hover:text-black"><FiX size={32}/></button>
                <div className="flex items-center gap-4 mb-10">
                  <div className="w-14 h-14 bg-black text-white rounded-2xl flex items-center justify-center"><FiFileText size={24} /></div>
                  <h3 className="text-4xl font-black uppercase tracking-tighter italic">Clinical Insight</h3>
                </div>
                <p className="text-xl font-medium leading-relaxed mb-10 opacity-80">{data.llm_generated_explanation.summary}</p>
                <div className="bg-red-600 text-white p-8 rounded-3xl">
                  <p className="text-[10px] font-black uppercase tracking-widest opacity-60 mb-2">Protocol Suggestion</p>
                  <p className="text-2xl font-black uppercase tracking-tight">{data.clinical_recommendation.recommendation}</p>
                </div>
              </motion.div>
            </div>
          )}
        </AnimatePresence>
      </main>
    </div>
  );
};

export default Analytics;